{% set name = "kernel-tuner" %}
{% set version = "1.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/kernel_tuner/kernel_tuner-{{ version }}.tar.gz
  sha256: 7d868c36561c090bfc7d83df578edf7b9ead05bee2147e849b56dc8139473cca

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - poetry-core >=1.7.0
    - python {{ python_min }}
    - setuptools >=67.7.2
  run:
    - __unix
    - jsonschema
    - numpy >=2.0.0
    - packaging
    - python-constraint2 >=2.3.1
    - pandas >=2.0.0
    - python >={{ python_min }},<4
    - scikit-learn >=1.0.2
    - scipy >=1.14.1
    - xmltodict

test:
  commands:
    - pip check
    - pytest -k 'not test_memcpy_dtoh and not test_memcpy_host_htod and not test_refresh_memory'
  imports:
    - kernel_tuner
  requires:
    - mock
    - pep440
    - pip
    - pytest >=7.4
    - pytest-cov
    - tomli
    - python {{ python_min }}
  source_files:
    - pyproject.toml
    - test
    - README.md

about:
  home: https://github.com/kerneltuner/kernel_tuner
  summary: 'An easy to use CUDA/OpenCL kernel tuner in Python'
  description: |
    Kernel Tuner simplifies the software development of optimized and
    auto-tuned GPU programs, by enabling Python-based unit testing of GPU code
    and making it easy to develop scripts for auto-tuning GPU kernels. This
    also means no extensive changes and no new dependencies are required in the
    kernel code. The kernels can still be compiled and used as normal from any
    host programming language.

    Kernel Tuner provides a comprehensive solution for auto-tuning GPU
    programs, supporting auto-tuning of user-defined parameters in both host
    and device code, supporting output verification of all benchmarked kernels
    during tuning, as well as many optimization strategies to speed up the
    tuning process.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://kerneltuner.github.io

extra:
  recipe-maintainers:
    - benvanwerkhoven
    - bouweandela
    - fjwillemsen
    - isazi
